apiVersion: 1

datasources:
  - name: InfluxDB
    uid: influxdb
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    database: sensors
    user: telegraf
    isDefault: true
    editable: true
    jsonData:
      httpMode: GET
      dbName: sensors
      version: InfluxQL
      timeInterval: 5s
    secureJsonData:
      password: telegraf
